export interface Project {
    title: string,
    description: string,
    image: string,
    tags: string[],
    source: string,
    visit: string,
    featured: boolean,
};

export const projects: Project[] = [
    {
        title: 'Brewin Language Interpretter',
        description: 'An interpretted and statically typed programming language built in pure Python. Includes I/O, primitives, objects, looping, functions and lexical scoping. Also supports error handling.',
        image: '/images/brewin-logo.png',
        tags: ['Python'],
        source: 'https://github.com/rudyorre/brewin',
        visit: '',
        featured: true,
    },
    {
        title: 'TensorFaux Library',
        description: "A neural network library which utilizes a similar API to TensorFlow Keras. Written in just Python/Numpy, and includes a documentation website and is accessible via PIP.",
          image: '/images/tensorfaux.png',
          tags: ['Python', 'Numpy', 'PIP'],
        source: 'https://github.com/rudyorre/TensorFaux',
        visit: 'https://rudyorre.github.io/TensorFaux',
        featured: true,
    },
    {
        title: 'Dash',
        description: "A minimal and dynamic dashboard interface. Dashboard and chart view definitions are stored in Supabase in addition to the raw data.",
        tags: ['Next', 'Express', 'Supabase', 'Postgres'],
        image: '/images/dash.png',
        source: 'https://github.com/rudyorre/dash',
        visit: '',
        featured: false,
    },
    {
        title: 'Chatbot.ai',
        description: "A chatbot interface that uses NLP to convert natural language into SQL queries. Built for JPL FireSat.",
        tags: ['Flask', 'NLTK', 'SparQL', 'Docker'],
        image: '/images/chatbotai.png',
        source: 'https://github.com/rudyorre/chatbot.ai',
        visit: '',
        featured: true,
    },
    {
        title: 'UCLA Theta Tau Website',
        description: 'Built the new site for UCLA Theta Tau from the ground up.',
        tags: ['React', 'Gatsby'],
        image: '/images/tt.png',
        source: 'https://github.com/UCLATT/thetataubruins.org',
        visit: 'https://thetataubruins.org',
        featured: true,
    },
    {
        title: 'ViT: Vision Transformer',
        description: 'An implementation of the Vision Transformer in Pytorch. ViT processes an input image as a sequence of patches and then feeds these patches to a transformer-based network.',
        image: '/images/vit.png',
        tags: ['PyTorch'],
        source: 'https://github.com/rudyorre/vit',
        visit: '',
        featured: true,
    },
    {
        title: 'Parts-of-Speech Tagger',
        description: 'Parts-Of-Speech (POS) tagger using Hidden Markov Models (HMM) and the Viterbi algorithm. Trained on a pre-tagged corpus and integrates NLTK\'s version for comparison.',
        image: '/images/pos-tagger.jpg',
        tags: ['Python', 'NLTK'],
        source: 'https://github.com/rudyorre/pos-tagger',
        visit: '',
        featured: true,
    },
    {
        title: 'N-Gram Language Model',
        description: 'An n-gram language model that implements add-k smoothing and greedy sentence generation. This model probabilistically predicts the rest of a sentence via an (n - 1)-order Markov model.',
        image: '/images/ngram.png',
        tags: ['Python', 'NLTK'],
        source: 'https://github.com/rudyorre/ngram',
        visit: '',
        featured: true,
    },
    {
        title: 'Tinder for Restuarants',
        description: "Matches users to restaurants based off of their preferences using a swiping feature similar to Tinder. User filters and preferences persist via MongoDB.",
          image: '/images/scramble.png',
          // tags: ['Mongo', 'Express', 'React', 'Node', "Yelp Fusion"],
          tags: ['MERN', 'Yelp API'],
        source: 'https://github.com/rudyorre/restaurant-tinder',
        visit: '',
        featured: true,
    },
    {
        title: 'Cannabis Sales Forecasting',
        description: "Developed a predictive model for sales forecasting and determined key success factors using ensemble methods such as Random Forest and Gradient Boosting.",
          image: '/images/cookies.png',
          tags: ['Pandas', 'Sci-Kit Learn'],
        source: 'https://github.com/rudyorre/m148-project3',
        visit: '',
        featured: true,
    },
    {
        title: 'Multivariable Linear Regression',
        description: 'Statistical model that uses N parameters to predict the outcome of the response variable. Implemented with the gradient descent aglorithm purely in C++.',
        image: '/images/multivariatelinearregression.png',
        tags: ['C++'],
        source: 'https://github.com/rudyorre/machine-learning-projects/tree/master/Multivariate-Linear-Regression',
        visit: '',
        featured: false,
    },
    {
        title: 'C++ Shared Pointer',
        description: "Simulates the C++ implementation of the shared pointer. This implementation has all of the important features, including templating so any object can be pointed to.",
        image: '/images/smartpointer.png',
        tags: ['C++'],
        source: 'https://github.com/rudyorre/smart-shared-ptr',
        visit: '',
        featured: false,
    },
    {
        title: 'C++ Map (BST Container)',
        description: "Implemented a C++ Map container built upon a binary search tree. Templated so any objects can be mapped, and prevents memory leaks in case of a allocation error.",
          image: '/images/bstmap.png',
          tags: ['C++'],
        source: 'https://github.com/rudyorre/El-Camino-College/tree/main/CS-30/Project%201.2%20-%20Map%20(Binary%20Search%20Tree)',
        visit: '',
        featured: false,
    },
    {
        title: 'Portfolio Site for Myself',
        description: "A simple website for showcasing some of my computer science projects. Static site built with React and hosted on Github Pages. More projects will be added in the near future.",
        image: '/images/portfolio.png',
        tags: ['React', 'NextJS'],
        source: 'https://github.com/rudyorre/rudyorre.com',
        visit: 'https://rudyorre.com/',
        featured: false,
    },
];