import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ThemeProvider } from '@/components/theme-provider'
import { UserNav } from '@/components/user-nav'
import { Search } from '@/components/search'
import { MainNav } from '@/components/main-nav'
import { ModeToggle } from '@/components/mode-toggle'
import { Background } from '@/components/background'
import Link from 'next/link'
import { Footer } from '@/components/footer'
import { cn } from '@/lib/utils'

import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [mouseX, setMouseX] = useState<number>(0);
  const [mouseY, setMouseY] = useState<number>(0);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      setMouseX(e.clientX);
      setMouseY(e.clientY);
    };

    document.addEventListener('mousemove', handleMouseMove);

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
    };
  }, []);

  return (
    <html lang="en" className='scroll-smooth'>
      <head>
        <title>Rudy Orre</title>
      </head>
      <body className={inter.className}>
          <ThemeProvider
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            themes={['light', 'dark', 'paper', 'carbon', 'bento', 'miami']}
          > 
            <Background />
            <div className={`border-b fixed top-0 z-20 w-screen backdrop-filter backdrop-blur-lg bg-background/[0.7]`}>
              <div className="flex h-16 items-center px-4 max-w-screen-xl mx-auto">
                <MainNav className="mx-6" />
                <div className="ml-auto flex items-center space-x-4">
                  <ModeToggle />
                </div>
              </div>
            </div>
            <div className="h-16"></div>
            <div className="bg-bg-color mx-auto max-w-screen-xl">
              {children}
            </div>
            <Footer />
          </ThemeProvider>
      </body>
    </html> 
  )
}
