import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import fs from 'fs';

import { ThemeProvider } from '@/components/theme-provider'
import { UserNav } from '@/components/user-nav'
import { Search } from '@/components/search'
import { MainNav } from '@/components/main-nav'
import { ModeToggle } from '@/components/mode-toggle'
import Link from 'next/link'
import { Footer } from '@/components/footer'
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className}>
          <ThemeProvider
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            themes={['light', 'dark', 'paper']}
          > 
            <div className={`border-b fixed top-0 z-20 w-screen backdrop-filter backdrop-blur-lg bg-background/[0.7]`}>
              <div className="flex h-16 items-center px-4 max-w-screen-xl mx-auto">
                <Link href="/" className="inline-flex">
                  <div className="font-extrabold">rudyorre</div>.com
                </Link>
                <MainNav className="mx-6" />
                <div className="ml-auto flex items-center space-x-4">
                  {/* <Search /> */}
                  {/* <UserNav /> */}
                  <ModeToggle />
                </div>
              </div>
            </div>
            <div className="h-16"></div>
            {children}
            <Footer />
          </ThemeProvider>
      </body>
    </html>
  )
}
